# General configuration
baseurl: "/openra-web" # the subpath of your site, e.g. /blog
url: "https://pchote.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OpenRA
github_username:  OpenRA
permalink: /:categories/:title/index.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "news/*"
    values:
      layout: "news" # set default layout for news posts

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# jekyll-feed configuration
title: OpenRA - News Feed 
description: >- # this means to ignore newlines until "baseurl:"
  Classic staregy games rebuilt for the modern era

feed:
  path: /news/atom.html # /news/atom.html -> /news/atom
